# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180424_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
