# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180424_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_display_images'),
        ),
    ]
