# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='collectibles',
            field=models.ManyToManyField(blank=True, to='games.Collectible'),
        ),
    ]
